[address]
ip = "0.0.0.0"
port = 25565

[settings]
enable_model_engine = false
max_world_tick_threads = 4
async_pathfinding_threads = 4
chunk_view_distance = 12
entity_view_distance = 8

[level]
default = { name = "debug", game_mode = "CREATIVE", spawn_position = { x = 0.0, y = 66.0, z = 0.0 } }

[[level.levels]]
name = "debug"
generator = "debug"
dimension_type = "minecraft:overworld"
save = false
entities = "level_entities/debug_level_entities.yml"
