[address]
ip = "0.0.0.0"
port = 25565

[level]
default = { name = "debug", spawn_position = { x = 0.0, y = 66.0, z = 0.0 } }
levels = [
    { name = "debug", generator = "debug", dimension_type = "minecraft:overworld", save = false }
]
