[address]
ip = "0.0.0.0"
port = 25565

[settings]
enable_model_engine = false
chunk_view_distance = 12
entity_view_distance = 8

[level]
default = { name = "debug", game_mode = "CREATIVE", spawn_position = { x = 0.0, y = 66.0, z = 0.0 } }
levels = [
    { name = "debug", generator = "debug", dimension_type = "minecraft:overworld", save = false }
]
